name: run_hlint

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_hlint:
    name: Run HLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HLint
        run: |
          curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Run HLint script
        run: |
          ./scripts/check_hlint.sh
